<?xml version="1.0" encoding="utf-8"?><Database Name="CHGame" Class="CHGameDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC\SQLEXPRESS;Initial Catalog=CHGame;Integrated Security=True" SettingsObjectName="BLDAL.Properties.Settings" SettingsPropertyName="CHGameConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTHoaDon" Member="CTHoaDons">
    <Type Name="CTHoaDon">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGame" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Game_CTHoaDon" Member="Game" ThisKey="MaGame" OtherKey="MaGame" Type="Game" IsForeignKey="true" />
      <Association Name="HoaDon_CTHoaDon" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="MaTL" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TheLoai_Game_TheLoai" Member="Game_TheLoais" ThisKey="MaTL" OtherKey="MaTL" Type="Game_TheLoai" />
    </Type>
  </Table>
  <Table Name="dbo.CTNhomQuyen" Member="CTNhomQuyens">
    <Type Name="CTNhomQuyen">
      <Column Name="MaNhom" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaQuyen" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NhomQuyen_CTNhomQuyen" Member="NhomQuyen" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomQuyen" IsForeignKey="true" />
      <Association Name="Quyen_CTNhomQuyen" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game" Member="Games">
    <Type Name="Game">
      <Column Name="MaGame" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGame" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HinhDaiDien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaNSX" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Game_CTHoaDon" Member="CTHoaDons" ThisKey="MaGame" OtherKey="MaGame" Type="CTHoaDon" />
      <Association Name="Game_Game_TheLoai" Member="Game_TheLoais" ThisKey="MaGame" OtherKey="MaGame" Type="Game_TheLoai" />
      <Association Name="NhaSanXuat_Game" Member="NhaSanXuat" ThisKey="MaNSX" OtherKey="MaNSX" Type="NhaSanXuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_TheLoai" Member="Game_TheLoais">
    <Type Name="Game_TheLoai">
      <Column Name="MaGame" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTL" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Game_Game_TheLoai" Member="Game" ThisKey="MaGame" OtherKey="MaGame" Type="Game" IsForeignKey="true" />
      <Association Name="TheLoai_Game_TheLoai" Member="TheLoai" ThisKey="MaTL" OtherKey="MaTL" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTK" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HoaDon_CTHoaDon" Member="CTHoaDons" ThisKey="MaHD" OtherKey="MaHD" Type="CTHoaDon" />
      <Association Name="TaiKhoan_HoaDon" Member="TaiKhoan" ThisKey="MaTK" OtherKey="MaTK" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVienQuanLy" Member="NhanVienQuanLies">
    <Type Name="NhanVienQuanLy">
      <Column Name="MaTK" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LuongCoBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PhuCapTrachNhiem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="TaiKhoan_NhanVienQuanLy" Member="TaiKhoan" ThisKey="MaTK" OtherKey="MaTK" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaSanXuat" Member="NhaSanXuats">
    <Type Name="NhaSanXuat">
      <Column Name="MaNSX" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNSX" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhaSanXuat_Game" Member="Games" ThisKey="MaNSX" OtherKey="MaNSX" Type="Game" />
    </Type>
  </Table>
  <Table Name="dbo.NhomQuyen" Member="NhomQuyens">
    <Type Name="NhomQuyen">
      <Column Name="MaNhom" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhomQuyen_CTNhomQuyen" Member="CTNhomQuyens" ThisKey="MaNhom" OtherKey="MaNhom" Type="CTNhomQuyen" />
      <Association Name="NhomQuyen_TaiKhoan" Member="TaiKhoans" ThisKey="MaNhom" OtherKey="MaNhom" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Quyen_CTNhomQuyen" Member="CTNhomQuyens" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="CTNhomQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaTK" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="TaiKhoan_HoaDon" Member="HoaDons" ThisKey="MaTK" OtherKey="MaTK" Type="HoaDon" />
      <Association Name="TaiKhoan_NhanVienQuanLy" Member="NhanVienQuanLy" ThisKey="MaTK" OtherKey="MaTK" Type="NhanVienQuanLy" Cardinality="One" />
      <Association Name="NhomQuyen_TaiKhoan" Member="NhomQuyen" ThisKey="MaNhom" OtherKey="MaNhom" Type="NhomQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_NVQL" Member="View_NVQLs">
    <Type Name="View_NVQL">
      <Column Name="MaTK" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LuongCoBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PhuCapTrachNhiem" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_CTHD" Member="View_CTHDs">
    <Type Name="View_CTHD">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaGame" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenGame" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_HoaDon" Member="View_HoaDons">
    <Type Name="View_HoaDon">
      <Column Name="MaHD" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaTK" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.View_Game" Member="View_Games">
    <Type Name="View_Game">
      <Column Name="MaGame" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenGame" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HinhDaiDien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaNSX" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TenNSX" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>